Iss hipcms 666 implement role check using authv3
HiP-App/HiP-FeatureToggle pull request #19
Opened 2017-08-16 18:40 UTC by nagaraj1993

2017-08-24 12:32 UTC, janis-kra requested changes
Requsted a few changes that I did not think of before. Apart from that, good job. When you applied the changes just have someone else do a quick review. Everything else is fine I already tested it. Or just wait until I return ;)

If you don't have the time to implement the changes because you're going on vacation, maybe ping Sven and ask if he can do it. Otherwise I'll do it next week when I return.

2017-08-24 12:32 UTC, janis-kra commented on HiP-FeatureToggle/Controllers/FeatureGroupsController.cs
> +    [Authorize]
I think we should set this to `Authorize("read:featuretoggle")`, so all calls to this API require the `"read:featuretoggle"` scope. Additionally, for all calls that require write privileges, the `"write:featuretoggle"` scope should be required (see below)

2017-08-24 12:32 UTC, janis-kra commented on HiP-FeatureToggle/Controllers/FeatureGroupsController.cs
>          [ProducesResponseType(422)]
Add `[Authorize("write:featuretoggle")]` here, s.t. ppl without write privileges cannot call this method. Same for all other POST, PUT or DELETE calls in all the contorllers.

2017-08-24 12:32 UTC, janis-kra commented on HiP-FeatureToggle/Controllers/FeaturesController.cs
> +    [Authorize]
See the comment in the other controller

2017-08-24 12:32 UTC, janis-kra commented on HiP-FeatureToggle/Startup.cs
> +            ToggleDbContext dbContext, IOptions<AuthConfig> authConfig)
missing a newline here

2017-08-26 11:47 UTC, nagaraj1993 commented
Resharper check in TFS fails and hence build is getting partially
succeeded. I don't know why this error suddenly came so wierd which did
not come up in the previous commits. So I added the check which resharper suggested too but still the problem exists. Please check details. Keeping this open till @janis-kra is back from Vacation.

2017-09-07 13:41 UTC, janis-kra commented on HiP-FeatureToggle/Startup.cs
> +            //Adding authorization
by the way, you can trigger new builds via TFS

2017-09-07 13:43 UTC, janis-kra commented
The reason your NullReference check did not get rid of the R# error is that a `catch` block only catches errors that occur within the `try` block. The potential error that R# reported would have occured within another `catch` block and would thus not have been caught by your check

2017-09-07 13:49 UTC, janis-kra approved these changes

2017-09-07 13:50 UTC, merged