Management of features
HiP-App/HiP-FeatureToggle pull request #3
Opened 2017-04-11 15:12 UTC by SvenEV

Besides the new features for HIPCMS-603, this PR includes improvements for feature group management (HIPCMS-602), especially regarding error handling (some HTTP status codes have changed).

2017-04-11 16:37 UTC, janis-kra requested changes
Few small changes. Apart from that, looks good 👍

2017-04-11 16:37 UTC, janis-kra commented on HiP-FeatureToggle/Controllers/FeatureGroupsController.cs
> +        [ProducesResponseType(409)]
It would be awesome if you would add a comment for these more exotic status codes, like this: `/// <response code="409">blabla</response>`

2017-04-11 16:37 UTC, janis-kra commented on HiP-FeatureToggle/Controllers/FeaturesController.cs
> +        [ProducesResponseType(409)]
Also produces response type 422 (if the given parentId is not found)

2017-04-11 16:37 UTC, janis-kra commented on HiP-FeatureToggle/Controllers/FeaturesController.cs
> +        public IActionResult Delete(int featureId)
I was able to delete a feature that was the parent of other features -- could be problematic as this destroyes the whole hierarchy (the chidl features were still existing after deleting the parent, with the `parent` attribute set to null)

My advice would be not allowing deletion of a parent feature at all; alternatively you could also delete all the child features

2017-04-11 16:38 UTC, janis-kra commented on HiP-FeatureToggle/Controllers/FeatureGroupsController.cs
> +        [ProducesResponseType(409)]
Okay forget it, not that important... only do it if you're bored ;)

2017-04-11 20:42 UTC, SvenEV commented on HiP-FeatureToggle/Controllers/FeaturesController.cs
> +        public IActionResult Delete(int featureId)
Regarding feature deletion see FeaturesManager, line 62. I have thought about that too and have (for now) decided to "pull-up" the children of the deleted feature and make them children of the deleted feature's parent. But of course I can change this behavior if desired.

So in your case you probably deleted a root feature (parent == null) which resulted in the children becoming root features.

2017-04-12 06:18 UTC, janis-kra commented
Okay, works for me.

2017-04-12 07:04 UTC, janis-kra commented on HiP-FeatureToggle/Controllers/FeaturesController.cs
> +        public IActionResult Delete(int featureId)
Okay, works for me.

2017-04-12 07:05 UTC, janis-kra approved these changes

2017-04-12 07:05 UTC, merged